### ISSUE TITLE
Code for entity popularity

### ISSUE THREAD

**Issue by PlusRoss** [AlexTMallen/adaptive-retrieval#2]
Hi,

Thanks for the great work! It seems that there's no code for computing entity popularity. Any plan to release that too?

**Comment by AlexTMallen** [comment]
Hi, thank you for your interest! In order to obtain the popularity for each entity, we use the following code: 

```
wiki_title = # Title of wikipedia page
headers = {'User-Agent': '<YOUR HEADERS INFO AND EMAIL>'}
url = 'https://wikimedia.org/api/rest_v1/metrics/pageviews/per-article/en.wikipedia/all-access/all-agents/{}/monthly/2021100100/2021103100'
resp = requests.get(url.format(wiki_title), headers=headers)
views = resp.json()['items'][0]['views']
```
For example, to access the results for the page titled "George Rankin", we use [https://wikimedia.org/api/rest_v1/metrics/pageviews/per-article/en.wikipedia/all-access/all-agents/George_Rankin/monthly/2021100100/2021103100](https://wikimedia.org/api/rest_v1/metrics/pageviews/per-article/en.wikipedia/all-access/all-agents/George_Rankin/monthly/2021100100/2021103100). Wikidata contains the Wikipedia page title for all entities that have a Wikipedia page (which is the vast majority of wikidata entities).
